### ISSUE TITLE
Failed to launch Scrap Mechanic -- CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by kibiz0r** [yodarocks1/ConstructModLoader#1] opened 2020-05-24 16:42 UTC
V+A.0.0-h2

I think you already know about this one, but just to keep eyes on it...

We will watch your career with great interest.

```
C:\WINDOWS\system32>java -jar "C:\Program Files (x86)\Construct\API\Construct Mod Loader.jar"
Getting active modifications

------- Modifications -------
  ? [Mod] Dev Mode Mod - Active
  ? [Mod] Example Modpack - Disabled
  ? [Mod] Marker Mod - Disabled
  ? [Mod] Super-Woc Mod - Disabled
May 24, 2020 12:35:17 PM cml.GUI lambda$start$6
SEVERE: Failed to launch Scrap Mechanic
java.io.IOException: Cannot run program "start": CreateProcess error=2, The system cannot find the file specified
```

**Comment by dentolos19** [comment] 2020-05-25 08:33
You installed Scrap Mechanic in a different folder right? That might be the problem as you can see [here](https://github.com/yodarocks1/ConstructModLoader/blob/master/src/cml/Constants.java). The folder location is fixed, so maybe the only way to fix this is by changing that **hard-coded value** to the correct folder.

**Comment by yodarocks1** [comment] 2020-05-25 23:48
Thanks for the heads up.
It seems the issue is with the start command. It should open the Windows Run... dialog, then pass the arguments to that, but it doesn't seem to be doing so. I'll be fixing it in the next update.

**Comment by yodarocks1** [comment] 2020-05-26 21:09
Fixed in V+A.1.0

Changed:
```
Constants.class
 ---
Removed: "start steam://rungameid/387990"
Added: "rundll32 url.dll,FileProtocolHandler steam://rungameid/387990"
```

**Closed as completed by yodarocks1** 2020-05-26 21:09 UTC
Labels: bug
